name:                llvc
version:             0.1.0.0
github:              "ucsd-progsys/llvc"
license:             MIT 
author:              "Ranjit Jhala"
maintainer:          "jhala@cs.ucsd.edu"
copyright:           "2018 Ranjit Jhala"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ucsd-progsys/llvc#readme>

dependencies:
- base >= 4.7 && < 5
- cmdargs
- process
- directory
- filepath
- hashable 
- containers
- unordered-containers
- megaparsec
- text

data-files:
- include/prelude.smt2
 
library:
  source-dirs: src
  ghc-options:
    - -Wall 


executables:
  llvc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall 
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - llvc

tests:
  llvc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - llvc
